services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/frontend:${TAG}"  
    ports:
      - "80:80" 
    environment:
      - SERVER_NAME=studytimer.com
      - BACKEND_PORT=5000
      - BACKEND_NAME=backend
    depends_on:
      - backend 

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/backend:${TAG}"  
    ports:
      - "5000:5000" 
    environment:
      - NODE_ENV=production
