# docker-compose.yml
version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80" # Maps port 80 on the host to port 80 in the container

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Maps port 5000 on the host to port 5000 in the container
    environment:
      - NODE_ENV=production
