# docker-compose.yml
services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80" # HTTP
    environment:
      - SERVER_NAME=studytimer.com
      - BACKEND_PORT=5000
      - BACKEND_NAME=backend
    depends_on:
      - backend # Ensure frontend starts after backend

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000" # Maps port 5000 on the host to port 5000 in the container
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/data:/app
