name: Docker Image CI

on:
  push:
    branches:
      - main
      - beta
      - mvp
      - prototype
  pull_request:
    branches:
      - main
      - beta
      - mvp
      - prototype

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js and run tests in frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      # Run backend test before building
      - name: Install Backend Dependencies
        run: |
          cd ./server
          npm install
          npm test
        env:
          CI: true

      # If test complete run docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker image tag
        id: tag
        run: |
          BASE_TAG=$(echo "${GITHUB_REF_NAME}" | grep -oE "main|beta|mvp|prototype")
          IMAGE_TAG="${BASE_TAG}-${NEW_VERSION}"
          LATEST_BRANCH_TAG="${BASE_TAG}"

          if [ -z "$BASE_TAG" ]; then
            echo "Error: BASE_TAG is empty. Ensure branch name matches one of the expected values."
            exit 1
          fi

          IMAGE_TAG="${BASE_TAG}-${NEW_VERSION}"
          LATEST_BRANCH_TAG="${BASE_TAG}"

          echo $((NEW_VERSION + 1)) > version.txt

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "LATEST_BRANCH_TAG=$LATEST_BRANCH_TAG" >> $GITHUB_ENV

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.LATEST_BRANCH_TAG }},${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.BASE_TAG }}"

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/backend:${{ env.LATEST_BRANCH_TAG }},${{ secrets.DOCKER_USERNAME }}/backend:${{ env.BASE_TAG }}"
