name: Docker Image CI

on:
  push:
    branches:
      - '*'       
  pull_request:
    branches:
      - '*'       

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '(?<="tag_name": ")[^"]*')
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker image tag
        id: tag
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA::7}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV

      - name: Build and Test with Docker Compose
        run: docker-compose -f docker-compose.yml build --abort-on-container-exit
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          TAG: ${{ env.TAG }}

      - name: Push Frontend Docker Image
        run: |
          docker-compose -f docker-compose.yml push frontend

      - name: Push Backend Docker Image
        run: |
          docker-compose -f docker-compose.yml push backend
