name: Docker Image CI

on:
  push:
    branches:
      - main
      - beta
      - mvp
      - prototype
  pull_request:
    branches:
      - main
      - beta
      - mvp
      - prototype

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js and run tests in frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      # Run backend test before building
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Jest Tests
        working-directory: ./backend
        run: npm test
        env:
          CI: true

      # If test complete run docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker image tag
        id: tag
        run: |
          BASE_TAG=$(echo "${GITHUB_REF_NAME}" | grep -oE "main|beta|mvp|prototype")
          IMAGE_TAG="${BASE_TAG}-${NEW_VERSION}"
          LATEST_BRANCH_TAG="${BASE_TAG}"

          NEW_VERSION=$(cat version.txt 2>/dev/null || echo "0.1")
          echo $((NEW_VERSION + 1)) > version.txt

          export IMAGE_TAG
          export LATEST_BRANCH_TAG

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.LATEST_BRANCH_TAG }}, ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.BASE_TAG }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.LATEST_BRANCH_TAG }}, ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.BASE_TAG }}
